### ISSUE TITLE
About cl_ragdoll_collide and ragdoll_sleepaftertime

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#206]
`cl_ragdoll_colide`: How does it works exactly?

And, why `ragdoll_sleepaftertime` has his default value with the letter `f`? Is that necessary?

**Comment by mastercoms** [comment]
The physics system by default checks if either object in a collision is a ragdoll. If so, it does not allow collision. Enabling cl_ragdoll_collide makes it so it does not block collision from this check.

ragdoll_sleepaftertime is 5.0f by default. Any other variation will be marked as modified. It's a small benefit to make it unmodified (I believe some servers check it), since we are setting it to 5 anyways.

**Comment by Tiagoquix** [comment]
@mastercoms Shouldn't `cl_ragdoll_colide` be disabled by default? Since it allows collisions, it may cause a disadvantage.

**Comment by mastercoms** [comment]
It's already 0 by default in TF2. Also it doesn't cause a disadvantage, it's just ragdolls colliding with each other.

**Comment by Tiagoquix** [comment]
> It's already 0 by default in TF2. Also it doesn't cause a disadvantage, it's just ragdolls colliding with each other.

All right. Just a note: `cl_ragdoll_colide` is enabled in `ragdolls_high`.
