### ISSUE TITLE
Use nawk instead of awk

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#477]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am forced to use bloated/featureful  GNU tools that are slower than counterparts.

**Describe the solution you'd like**
Replace the awk (which is most likely symlinked to gawk) with nawk.

**Describe alternatives you've considered**
mawk, but nawk was faster in my tests

**Additional context**
Mastercomfig is about micro optimizations and I think is a good micro optimization.
https://docs.mastercomfig.com/en/latest/tf2/

**Comment by ghost** [comment]
A whopping 500ms faster.
Since nawk isn't installed on most systems by default that means you'll have to install it manually which nullifies any speed gained from running nawk in the first place.

`hyperfine --warmup 5 --min-runs 20 'find . -type f \( -name "*.so" -o -name "hl2_linux" \) -print0 | xargs -0 strings | grep "^\-[A-Za-z]" | awk 'NF==1' | sort -u > launch_options.txt' 'find . -type f \( -name "*.so" -o -name "hl2_linux" \) -print0 | xargs -0 strings | grep "^\-[A-Za-z]" | nawk 'NF==1' | sort -u > launch_options.txt' --export-markdown output.md`

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `find . -type f \( -name "*.so" -o -name "hl2_linux" \) -print0 \| xargs -0 strings \| grep "^\-[A-Za-z]" \| awk NF==1 \| sort -u > launch_options.txt` | 6.524 ± 0.230 | 6.263 | 7.190 | 1.02 ± 0.04 |
| `find . -type f \( -name "*.so" -o -name "hl2_linux" \) -print0 \| xargs -0 strings \| grep "^\-[A-Za-z]" \| nawk NF==1 \| sort -u > launch_options.txt` | 6.368 ± 0.139 | 6.173 | 6.594 | 1.00 |

**Comment by micwoj92** [comment]
> Since nawk isn't installed on most systems by default that means you'll have to install it manually which nullifies any speed gained from running nawk in the first place.

Using the same logic I can say that coreutils rewritten in rust are not installed by default on systems and it would nullify any speed gained from running them in first place, yet some people still want to use them. Or maybe some there is some gnu awk rust rewrite that is faster and I am not aware of it? Anyway, thanks for confirming the tests on your system (with much longer testing than I did). I think that with sample size being two times as big now, we can clearly see that it is improvement.
