### ISSUE TITLE
Setting Post-Processing below "High" breaks the cubemaps for select maps

### ISSUE THREAD

**Issue by fdils** [mastercoms/tf2cfg#576]
**Describe the bug**
If post-processing is set to anything below "high" in modules.cfg, the cubemaps for specific maps (ie. 2Fort, Sawmill, Well, Watchtower) will fail to load, and the following error will appear in console for each cubemap texture:

Requesting texture value from var "$basetexture" which is not a texture value (material: skybox/...)

After rebuilding the cubemaps, the error will no longer occur, but the resulting map file becomes incompatible with vanilla servers.

**How you encountered the issue**
After downloading a clean installation of TF2, install mastercomfig with the "None" preset and "post_processing=high" in the modules.cfg file. Load up one of the previously mentioned maps (2Fort's cubemaps would sometimes work even if the error was thrown, but Watchtower was very consistent) and observe the water's reflections working normally. Restart the game with post_processing now set to "medium" or "low," and re-open the map with now pitch-black water.

**Screenshots**
Watchtower with "post_processing=medium"
![water_medium](https://user-images.githubusercontent.com/77127060/131417267-c1878590-0dbf-4b75-85c7-2974cc6aaaad.png)

Watchtower with "post_processing=high"
![water_high](https://user-images.githubusercontent.com/77127060/131417284-9937b4dc-2774-45fb-a9cd-e9a9cfcbd9ad.png)

**Desktop (please complete the following information):**
* mastercomfig version: 9.5.2
* Preset and addon(s): None with no addons
* Custom values (if any): post_processing=high, post_processing=medium/low
* DX level: 100
* Launch options: -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars
* Operating system (OS): Windows 10 Pro
* Graphics card (GPU): AMD Radeon RX 5700 XT
* Graphics driver version: 21.8.1
* Processor (CPU): AMD Ryzen 9 3900X
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 32 GB

**Comment by mastercoms** [comment]
Thanks so much for tracking down this bug!

**Comment by treacherousfiend** [comment]
I believe this is not entirely a comfig issue, as the console errors (or at least, the skybox ones) happen even when running with -default!

I've actually done a bit of research into this bug beforehand, and it seems like just about all the materials that cause errors are map created ones that parent the actual material, with the texture var supposed to be set by said material, so it seems like something is happening to cause it to fail to mount that. the materials they load _do_ have the texture vars that they call, but for some reason the game is failing to load them

It seems like something in comfig exasperates the issue and causes error spam for water materials in the map as well as the skybox, although I couldn't get reflections to work with only the skybox errors on -default

here's some images of the console errors on watchtower:
-default
![image](https://user-images.githubusercontent.com/46549454/131420757-ffb65a37-f98e-46bc-bd00-c304abffcacf.png)

my comfig setup with post_processing=off:
![image](https://user-images.githubusercontent.com/46549454/131420890-d5d0dc21-1dee-44fe-b488-780395ed3b10.png)

**Comment by itVictor** [comment]
Very annoying issue (especially for water) that I've been dealing for quite a while (mostly on custom maps), nice to see that people are trying to look into it. Some thoughts:

1. It is not config related; I've seen this issue happen in other source games and on a clean install of tf2.
2. the issue will go away if you manually build cubemaps for the map(s) in question, your game will crash because it already has cubemaps built in, but on next launch the textures will load correctly. 
3. Not 100% confirmed, but me and everyone who've I talked too that had this issue reported they had a AMD gpu, iirc at least one person who had the issue said it went away after they switched to an NVIDIA gpu. If that's something you can test it's definitely worth investigating if it's a gpu driver problem.

**Comment by treacherousfiend** [comment]
I have an nvidia GPU, so its not that, literally from what I can tell is just that for some reason the game is failing to load the "include" statement in the vmt correctly.
For example, here's what the water material that is erroring out in my image has for its vmt file
```
"patch"
{
	"include"		"materials/WATER/WATER_2FORT.vmt"
	"replace"
	{
		"$envmap"		"maps/arena_watchtower/c-32_-864_96"
		"Proxies"
		{
		}
	}
}
```
If you look at the material it includes (not including water_2fort.vmt here because of how long it is), it _does_ have all of the right texture variables (in this case: $fogenable, $fogcolor, $fogstart, and $fogend).

Another interesting thing is that it only seems to happen with some textures that are embedded in the map. Others that are completely identical (like a cubemap for a different part of the map) will work perfectly fine despite having the exact same material file.

In the case of the skybox error, this happens even if the skybox isn't embedded in the map, but for some reason it complains about $basetexture, which is essentially the material file telling the engine what actual texture to use. Despite all this, the skybox still works for some reason.

My guess is that the game is doing something like this
1. load material file from map
2. start loading material file from "include" statement
3. load next material file from map
4. attempt to start loading material file from "include" statement
5. we're already loading that file!

at this point, the second material attempts to continue, but the game hasn't told it where the "include" material is in memory, because its already loading the texture and just ignores the attempt to load it again, so it throws errors
meanwhile, the first material works fine because it was told where the material would be. (or was told after the material finished loading)
Any materials loaded afterwards probably get told where the material is because its already loaded, so this is probably a weird edge case where a material with an "include" statement is loaded while its "include" target is still being loaded, which the game isn't set up to handle so it just ignores it.

**Comment by itVictor** [comment]
One thing I forgot to mention: For some strange reason (on the custom maps that have this problem), deleting the bsp and redownloading it from somewhere **after doing the build cubemaps workaround,** the issue is not present on the newly downloaded bsp.

**Comment by mastercoms** [comment]
Unfortunately these maps aren't properly made to support all setting cases, there's nothing we can do to fix it besides having the user choose their preferred performance vs. visual glitches balance.
