### ISSUE TITLE
Issues with weapon binds

### ISSUE THREAD

**Issue by DeBozMann** [mastercoms/tf2cfg#69]
I use the crosshair switcher from cfg.tf. When I use this with it, it rebinds 1, 2 and 3 to w1, w2 and w3 respectively. There is nothing I can do to fix this so for now I just don't use mastercomfigs. If there is a fix, please let me know.

**Comment by JarateKing** [comment]
First add `exec binds; exec settings; exec network` to `cfg/custom.cfg`. This is because with mastercomfig, your autoexec is overridden but it supports custom.cfg instead. The only other things that should be in your autoexec from cfg.tf are `exec gfx; exec custom` but you shouldn't put those in custom.

Then rename `demoman.cfg`, `engineer.cfg`, etc. to `demoman_c.cfg`, `engineer_c.cfg`, etc. This is because of the same logic as above.

<hr>

Alternatively, if you don't care about anything else from cfg.tf and just want the crosshair switcher, you can:

1. Make sure that your still have the `crosshairswitcher` folder in your `cfg` folder.
1. Create a `scout_c.cfg` and add `exec crosshairswitcher/switcher; scout` to it. Repeat for all other class cfg's.

**Comment by DeBozMann** [comment]
Is the process the same if I apply mastercomfigs using the mastercomfigs app? Sorry if this is an obvious question, its just that with the app you put a .vpk file in your tf/custom, but if its done through cfg.tf it just makes a gfx.cfg file in tf/cfg.

**Comment by JarateKing** [comment]
Yep. The .vpk file contains the same overrides for autoexec / class cfg's / etc. regardless of what's in the cfg folder. The mastercomfig autoexec (that exists in the vpk) will run custom.cfg so you put your changes in there, the class cfg's will run their _c versions, etc.
