### ISSUE TITLE
Could you make a version for TF2 Classic and Open Fortress please?

### ISSUE THREAD

**Issue by Leololgithub** [mastercoms/tf2cfg#754]
**Is your feature request related to a problem? Please describe.**
When using mastercomfig on tf2 mods some issues can come like error particles if you set custom explosions or some bugs

**Describe the solution you'd like**
I would like mastercomfig versions for TF2C and Open Fortress

**Describe alternatives you've considered**
I have none

**Additional context**
When i used mastercomfig on TF2C, error particles would appear instead. Probably because i have very low particles or custom explosions enabled.
IDK, these mods would run better if there would be a mastercomfig version for both these mods for people that have low end hardware.

**Comment by treacherousfiend** [comment]
Duplicate of #60 
While the issue is 6 years old at this point, the tl;dr is that a more general and flexible system for having matercomfig versions for different games is still in the works.

One of the big issues with it is simply that despite being on the same engine, Source games are _VERY_ different from one another. Even in the case of TF2C and OF, while being built off of TF2, they are built off of a version of TF2 from leaked Orange Box code which is over a decade old. Despite being the same game, they are so far removed from modern day TF2 that many things that mastercomfig does in vanilla TF2 simply does not apply to TF2C and OF.
At the very leas, as far as I know the TF2C team (not sure about OF) is very dedicated to optimizing their game, so even without mastercomfig it should run better than modern TF2.

**Comment by zararashigal** [comment]
> Duplicate of #60 
> While the issue is 6 years old at this point, the tl;dr is that a more general and flexible system for having matercomfig versions for different games is still in the works.
> 
> One of the big issues with it is simply that despite being on the same engine, Source games are _VERY_ different from one another. Even in the case of TF2C and OF, while being built off of TF2, they are built off of a version of TF2 from leaked Orange Box code which is over a decade old. Despite being the same game, they are so far removed from modern day TF2 that many things that mastercomfig does in vanilla TF2 simply does not apply to TF2C and OF.
> At the very leas, as far as I know the TF2C team (not sure about OF) is very dedicated to optimizing their game, so even without mastercomfig it should run better than modern TF2.

Where can i contribute? How can i help? Is the branch closed source? Is it propietary? So many questions in my head about this vague answer.

**Comment by mastercoms** [comment]
It's not available yet. It will be made public when it's ready. It involves a lot of core design changes that I am working on myself, so it's not ready for open source contributions at this time.
